---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "romm.fullname" . }}-mysql-data
  labels:
    {{- include "romm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mariadb.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "romm.fullname" . }}-resources
  labels:
    {{- include "romm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.romm.persistence.resources.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "romm.fullname" . }}-redis-data
  labels:
    {{- include "romm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.romm.persistence.redisData.size }}
