apiVersion: v1
kind: Service
metadata:
  name: {{ include "romm.fullname" . }}
  labels:
    {{- include "romm.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.romm.service.type }}
  ports:
    - port: {{ .Values.romm.service.port }}
      targetPort: {{ .Values.romm.service.targetPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "romm.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
