apiVersion: v1
kind: Secret
metadata:
  name: {{ include "romm.fullname" . }}-secret
  labels:
    {{- include "romm.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWD: {{ required "secrets.dbPassword is required" .Values.secrets.dbPassword | quote }}
  MARIADB_ROOT_PASSWORD: {{ required "secrets.dbRootPassword is required" .Values.secrets.dbRootPassword | quote }}
  MARIADB_PASSWORD: {{ required "secrets.dbPassword is required" .Values.secrets.dbPassword | quote }}
  ROMM_AUTH_SECRET_KEY: {{ required "secrets.rommAuthSecretKey is required" .Values.secrets.rommAuthSecretKey | quote }}
  SCREENSCRAPER_PASSWORD: {{ .Values.romm.env.screenscraper.password | quote }}
  RETROACHIEVEMENTS_API_KEY: {{ .Values.romm.env.retroachievements.apiKey | quote }}
  STEAMGRIDDB_API_KEY: {{ .Values.romm.env.steamgriddb.apiKey | quote }}
  IGDB_CLIENT_ID: {{ .Values.romm.env.igdb.clientId | quote }}
  IGDB_CLIENT_SECRET: {{ .Values.romm.env.igdb.clientSecret | quote }}
