version: '3'
includes:
  fonts:
    taskfile: ./fonts/Taskfile.yml
    internal: false
    flatten: true
  oh-my-zsh:
    taskfile: ./oh-my-zsh/Taskfile.yml
    internal: false
    flatten: true

tasks:
  default:
    cmds:
      - task --list --dir .
    silent: true