---
name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: CI / Build   # <- this is the check name you’ll search for
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install the files
        run: |
          echo "$GITHUB_WORKSPACE"
          ./install.sh

      - name: Run source bashrc
        shell: bash
        run: |
          set -euo pipefail
          bash --login -c "source ~/.bashrc"
